GET http://localhost:3000/ HTTP/1.1

### Register User

POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "email": "String@mail.com",
    "password": "String323",
    "firstName": "First",
    "lastName": "Last",
    "birthDate": "01-11-1991"
}

### Login User

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "String@mail.com",
    "password": "String323"
    //"password": "String32223"
}

### Login Inexistent User

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "doesntExist@mail.com",
    "password": "String323"
}

### Get User Profile

GET http://localhost:3000/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN0cmluZ0BtYWlsLmNvbSIsImZpcnN0TmFtZSI6IlRlc3RBIiwibGFzdE5hbWUiOiJVc2VyIiwiYmlydGhEYXRlIjoiMTk5Mi0wMi0xMVQyMTowMDowMC4wMDBaIiwiaWF0IjoxNjQ1ODA5ODYzLCJleHAiOjE2NDU4OTYyNjN9.FdXlDzOz0ETlWxYQwnsFiqIdr6GLpz_4mHluDEc-GFI


### Update User Profile

PUT http://localhost:3000/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN0cmluZ0BtYWlsLmNvbSIsImZpcnN0TmFtZSI6IlRlc3RBIiwibGFzdE5hbWUiOiJVc2VyIiwiYmlydGhEYXRlIjoiMTk5Mi0wMi0xMVQyMTowMDowMC4wMDBaIiwiaWF0IjoxNjQ1ODA5ODYzLCJleHAiOjE2NDU4OTYyNjN9.FdXlDzOz0ETlWxYQwnsFiqIdr6GLpz_4mHluDEc-GFI

{
    "firstName": "TestAA",
    "lastName": "User",
    "birthDate": "02-12-1992"
}